декор
htmlacademy-htmlcss/1997001-sedona-33 pull request #7
Opened 2022-03-01 10:34 UTC by Denchik1213

2022-03-02 15:22 UTC, pavel-niukalo requested changes

2022-03-02 15:22 UTC, pavel-nyukalo commented on catalog.html
> +                            <button class="product-card-button-favorites decore-buttom" type="button"><span class="button-span">В избранное</span></button>
`decorate-buttoM` -> `decorate-button`

По поводу `span`.
1. Он выглядит лишним тегом, поскольку просто оборачивает текст. Можно стилизовать сразу через стили кнопки
2. `span` сделан для `opacity: 30%` при нажатии, но он работает не совсем корректно, а именно: стили `opacity` применятся тогда, когда я нажму точно по тексту, а если нажать не по тексту, но по кнопке (за пределами `span`, например вот сюда ![image](https://user-images.githubusercontent.com/52506235/156388911-85f3d5bc-e3e7-4782-8b49-ad5e845a390e.png)), то `opacity` уже не применится
3. В таких случаях, когда нам надо чему-то дать `opacity` (но оно влияет в целом на элемент, а нам например не надо чтобы фоновый цвет имел полупрозрачность, как в этом случае), стоит применить функцию [`rgba`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgba()) с альфа каналом

2022-03-02 15:22 UTC, pavel-niukalo commented on catalog.html
> +                <button class="button-loadmore" type="button"><span class="button-loadmore-span">Загрузить еще</span></button>
Тут тоже спан считаю лишним, + у него есть псевдоэлементы-линии. Я бы порассуждал с точки зрения дизайна и верстки. Кажется, что эти линии относятся к списку и пагинации, соответственно. Вдруг мы захотим добавить еще кнопку рядом с "Загрузить еще", получится вот это
![image](https://user-images.githubusercontent.com/52506235/156390218-c2552db4-d2ca-403a-bd01-da1ed1f92d02.png)

А так эти линии отделяют список и пагинацию от блока с кнопкой (кнопками)

2022-03-02 15:22 UTC, pavel-nyukalo commented on styles.css
> +  padding: 8px 10px 10px 10px;
Тут смотри сначала паддинги обнуляются, а потом все четыре паддинга задаются.
`padding: 0` тут явно лишний, стоит удалить

2022-03-02 15:22 UTC, pavel-nyukalo commented on styles.css
> +}
Про эти линии уже отписал выше, + смотри они дублируют друг-друга, за исключением `left`. Лучше объединить стили через `,`
```
...after,
...before {}
```

2022-03-04 16:40 UTC, pavel-nyukalo requested changes

2022-03-04 16:40 UTC, pavel-nyukalo commented on styles.css
> +.product-card::before{
Сейчас эта линия применяется к каждому `product-card` (то есть `li`), из-за этого появляется большой скролл горизонтальный 
![image](https://user-images.githubusercontent.com/52506235/156803101-326ef98a-da77-460d-9b3a-042b478e9407.png)

Поэтому лучше сделать его не каждому `product-card`, а всему блоку `ul`.
И это скорее `after` (после), чем `before` (до)

2022-03-04 16:40 UTC, pavel-nyukalo commented on styles.css
> +.pagination-box::after{
И здесь так же в именовании, тут больше подходит `before`, нежели `after`. По макету у нас эта линия _до_ пагинации

2022-03-09 15:07 UTC, pavel-nyukalo commented on styles.css
> +  outline: none !important;
По [критерию](https://up.htmlacademy.ru/htmlcss/33/criteries#CSS-05) нельзя использовать `important`

2022-03-09 15:12 UTC, pavel-nyukalo commented on styles.css
> +.input[type="emaill"]:invalid{
Скорее всего не будет работать, ибо `type` у нас `email`, а тут `emaill`

2022-03-09 15:18 UTC, pavel-nyukalo requested changes

2022-03-09 15:18 UTC, pavel-nyukalo commented on styles.css
> +  outline: none !important;
По [критерию](https://up.htmlacademy.ru/htmlcss/33/criteries#CSS-05) нельзя использовать `important`

2022-03-09 15:18 UTC, pavel-niukalo commented on styles.css
> +.input[type="emaill"]:invalid {
Скорее всего не будет работать, т.к в разметке у нас `type='email'`, а тут `emaill`

2022-03-11 16:45 UTC, pavel-nyukalo approved these changes

2022-03-11 16:45 UTC, merged